{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bubble.redis.fullname" . }}
  labels:
    {{- include "bubble.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "bubble.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
